export ZSH=$HOME/.oh-my-zsh

plugins=(git zsh-syntax-highlighting bundler brew gem)

source $ZSH/oh-my-zsh.sh

for file in ~/.{exports,aliases}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# PostgreSQL
export PATH="/usr/local/opt/postgresql@9.5/bin:$PATH"

# load pure prompt
fpath=("$HOME/.zfunctions" $fpath)
autoload -U promptinit && promptinit
prompt pure
